TARGET := wMusic-Bridge
PROJECT_HOME := /home/raphio/Development/wMusic/Bridge
INCLUDES_SRC := -I$(PROJECT_HOME)
INCLUDES_LIBS_HEADERS := -I/usr/local/include/
INCLUDES_HEADERS := -I/opt/cross/x-tools/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot/usr/include
CC := /opt/cross/x-tools/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-g++
GCC := /opt/cross/x-tools/arm-unknown-linux-gnueabi/bin/arm-unknown-linux-gnueabi-gcc
DEBUGFLAGS_C-Compiler := -g -O0 -fno-omit-frame-pointer -pipe -Wall
LIBS := -L/home/raphio/Development/wMusic/ARMLibs -lvlc -lspotify -lasound -lpthread-2.13 -lvlccore -ldbus-1 -lrt-2.13

OBJFILES := main.o \
	audio/audio.o \
	audio/alsa-audio.o \
	file/file.o \
	network/network.o \
	network/server.o \
	network/stream.o \
	spotify/account.o \
	spotify/playlist.o \
	spotify/player.o \
	spotify/search.o \
	spotify/playQueueManager.o \
	spotify/spotify.o \
	system/cli.o \
	system/environment.o \
	utils/thread.o \
	utils/trace.o \
	utils/zmemory.o \
	vlc/vlcManager.o

SRC := 	main.c \
	audio/audio.c \
	audio/alsa-audio.c \
	file/fileManager.c \
	network/network.c \
	network/server.c \
	network/stream.c \
	spotify/account.c \
	spotify/playlist.c \
	spotify/player.c \
	spotify/search.c \
	spotify/playQueueManager.c \
	spotify/spotify.c \
	system/cli.c \
	system/environment.c \
	utils/thread.c \
	utils/trace.c \
	utils/zmemory.c \
	vlc/vlcManager.c

%.o: %.c
	$(GCC) $(DEBUGFLAGS_C-Compiler) $(INCLUDES_SRC) $(INCLUDES_LIBS_HEADERS) -c -fmessage-length=0 -o $@ $<

all: $(OBJFILES)
	$(GCC) $(OBJFILES) -o $(TARGET) $(LIBS)
	rm -f $(OBJFILES)
	rm -f *.o

clean:
	rm -f $(OBJFILES) rm -f $(TARGET)

